#
###################################
# Site wide configuration
####################################
#
title: Ufuk Turuncoglu 
email: ufuk.turuncoglu@itu.edu.tr
description: Personal page of Ufuk Turuncoglu
url: https://uturuncoglu.github.io/ # the base hostname & protocol for your site
keywords: ["Earth System Model", "ESMF", "ParaView", "Scientific Visualization", "Numerical Modelling of Atmosphere and Ocean", "Scientific Workflows", "RegESM", "In-situ Visualization"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Istanbul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ufuk Utku Turuncoglu
  avatar: avatar.png
  job: "Assist. Prof."
  bio: "A scientist who study in computational earth system science field at Informatics Institute, Istanbul Technical University, Turkey"
  email: ufuk.turuncoglu@itu.edu.tr
  disqus-shortname: #renyuanzblog
  twitter: UfukTuruncoglu #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-36049219-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: uturuncoglu #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
